name: Update AGOL Hub Content

on:
  push:
    branches: [main, kevin-branch]
  schedule:
    - cron: '30 5 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: graydons_env
        python-version: 3.8

    - name: Install dependencies
      shell: bash
      run: |
        # throwing python version to verify its using the right version
        python --version
        cd /usr/bin/python
        ls -la
        #conda env update --file environment.yaml --name base
        #conda activate graydons_env
        
    - name: Run script
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{secrets.PASSWORD}}
      run: |
        python list_agol_hub_content.py
