name: Update AGOL Hub Content

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '30 5 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Miniconda
      shell: bash
      run: |
        wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        rm miniconda.sh
        export PATH=$HOME/miniconda/bin:$PATH
        conda init bash

    - name: Create Conda environment
      run: |
        conda create --name myenv python=3.8 -y
        conda activate myenv

    - name: Install ArcGIS API for Python
      run: |
        conda install -c esri arcgis -y

    - name: Run Python script
      run: python myscript.py
        
    - name: Run script
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{secrets.PASSWORD}}
      run: |
        python list_agol_hub_content.py
