name: Update AGOL Hub Content

on:
  push:
    branches:
      - ["main","kevin-branch"]
  schedule:
    - cron: '30 5 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: graydons_env
        python-version: 3.8

    - name: Install dependencies
      shell: bash
      run: |
        wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        rm miniconda.sh
        export PATH=$HOME/miniconda/bin:$PATH
        conda init bash

    - name: Configure conda
      run: |
        conda env update --file environment.yml --name base
        conda activate graydons_env
        
    - name: Run script
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{secrets.PASSWORD}}
      run: |
        python list_agol_hub_content.py
