name: Update AGOL Hub Content

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '30 5 * * 1'
  workflow_dispatch:

jobs:
  update_hub:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv
        python-version: 3.8

    - name: Install dependencies
      run: |
        conda activate myenv
        conda install --yes -c esri arcgis
        conda install --yes pandas
    
    - name: Run script
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{secrets.PASSWORD}}
      run: |
        python list_agol_hub_content.py
